use  hospital_database;

create table patient (
         patient_id int primary key,
         patient_name varchar(50) not null ,
         age int not null ,
         gender varchar(1) not null,
         mobile varchar(20) not null,
         address varchar(100) not null,
         date_of_admission date not null
);
 
create table doctor(
		doctor_id int primary key ,
        doctor_name varchar(50) not null,
        mobile varchar(20) not null,
        specialty varchar(50) not null
);
alter table doctor add department_id int not null  ;
alter table doctor add foreign key(department_id) references department(department_id);

create table department (
        department_id int primary key,
        department_name varchar(50)
);

create table appointment (
        appointment_id int primary key,
        patient_id int not null,
        doctor_id int not null,
        date_of_appointment date not null,
		diagonosis varchar(100),
        foreign key (patient_id) references patient(patient_id),
        foreign key (doctor_id) references doctor(doctor_id)
);

create table treatment(
		treatment_id int primary key,
        appointment_id int not null,
        treatment_desc varchar(100) not null,
        treatment_date date not null ,
        foreign key (appointment_id) references appointment(appointment_id) 

);

create table bill(
       bill_id int primary key,
       treatment_id int not null,
       amount bigint,
       paid_status varchar(1),
       paid_method varchar(50),
       foreign key (treatment_id) references treatment(treatment_id)
);
 
 
-- queries : 
-- list all patients and their treatment with doctor info
          select patient.patient_name,doctor.doctor_name,treatment.treatment_desc from appointment 
                 join patient on patient.patient_id=appointment.patient_id
                   join doctor on doctor.doctor_id = appointment.doctor_id
                     join treatment on treatment.appointment_id=appointment.appointment_id;
                    
-- list the number of patients treated by each doctor   
		  select doctor.doctor_name,count(appointment.patient_id) as no_of_patients from appointment 
                 join doctor on doctor.doctor_id = appointment.doctor_id group by doctor.doctor_name ;
                 
-- number of doctor in each department
         select department.department_name,count(doctor.department_id) as total_number from doctor 
              join department on department.department_id = doctor.department_id group by department.department_name;
              
-- list of patients having cost above 1000
           select patient.patient_name , bill.amount from patient 
                join appointment on appointment.patient_id = patient.patient_id
                   join treatment on treatment.appointment_id= appointment.appointment_id
					  join bill on  bill.treatment_id = treatment.treatment_id where bill.amount > 1000;

-- revenue generated by each doctor ;
            select doctor.doctor_name , bill.amount from doctor 
                join appointment on appointment.doctor_id = doctor.doctor_id
                    join treatment on treatment.appointment_id = appointment.appointment_id
                         join bill on bill.treatment_id = treatment.treatment_id ;
                            
            
            
		